
language: perl
perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

before_install:
    - sudo apt-get -y remove libzmq*

install:
    - cpanm --notest Perl::PrereqScanner

before_script:
    - >-
        cp $(which scan_prereqs) ./ &&
        ./scan_prereqs --combine lib t
        | grep -v ZMQ::FFI
        | awk '{ print $1 }'
        | cpanm --notest || /bin/true

script: xt/test_versions.sh
